[project]
name = "deepeyes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flash-attn>=2.8.3",
    "math-verify>=0.8.0",
    "openai>=1.108.1",
    "pytest>=8.4.2",
    "qwen-vl-utils>=0.0.13",
    "transformers<4.53",
    "verl",
    "vllm==0.9.1",
]

[tool.uv.sources]
verl = { path = "../../Repository/verl", editable = true }
