#!/bin/bash
# 示例：不同测试场景的使用方法

echo "=================================="
echo "📚 工具测试使用示例"
echo "=================================="

# 设置环境变量
export TOOL_SERVICE_IP=10.21.9.6

# 数据路径
BASEDIR=/app/xiaominl/datasets/air_d1_sp9_up2_bs128_n8_balanced

echo ""
echo "=================================="
echo "场景1: 快速测试（5个样本）"
echo "=================================="
echo "用于验证工具是否正常工作"
echo ""
echo "命令:"
echo "  bash tests/quick_test_tools.sh ${BASEDIR}/shard-test-000000.parquet ./quick_test"
echo ""

echo "=================================="
echo "场景2: 完整测试（所有样本，所有工具）"
echo "=================================="
echo "用于全面评估工具性能"
echo ""
echo "命令:"
echo "  python3 tests/test_all_tools_metrics.py \\"
echo "      --parquet ${BASEDIR}/shard-test-000000.parquet \\"
echo "      --output_dir ./full_test_results"
echo ""

echo "=================================="
echo "场景3: 测试特定工具"
echo "=================================="
echo "用于对比特定工具的性能"
echo ""
echo "命令:"
echo "  python3 tests/test_all_tools_metrics.py \\"
echo "      --parquet ${BASEDIR}/shard-test-000000.parquet \\"
echo "      --output_dir ./denoising_comparison \\"
echo "      --tools swinir_denoising mprnet_denoising \\"
echo "      --max_samples 50"
echo ""

echo "=================================="
echo "场景4: 批量测试多个分片"
echo "=================================="
echo "用于大规模评估"
echo ""
echo "命令:"
echo "  for i in {0..3}; do"
echo "      python3 tests/test_all_tools_metrics.py \\"
echo "          --parquet ${BASEDIR}/shard-test-00000\$i.parquet \\"
echo "          --output_dir ./results_shard_\$i \\"
echo "          --max_samples 100"
echo "  done"
echo ""

echo "=================================="
echo "场景5: 不保存图像（节省空间）"
echo "=================================="
echo "用于只关注指标数据"
echo ""
echo "命令:"
echo "  python3 tests/test_all_tools_metrics.py \\"
echo "      --parquet ${BASEDIR}/shard-test-000000.parquet \\"
echo "      --output_dir ./metrics_only \\"
echo "      --no_save_images"
echo ""

echo "=================================="
echo "场景6: 去模糊工具对比"
echo "=================================="
echo "用于评估所有去模糊工具"
echo ""
echo "命令:"
echo "  python3 tests/test_all_tools_metrics.py \\"
echo "      --parquet ${BASEDIR}/shard-test-000000.parquet \\"
echo "      --output_dir ./deblurring_tools \\"
echo "      --tools restormer_motion_deblurring \\"
echo "              restormer_defocus_deblurring \\"
echo "              xrestormer_motion_deblurring \\"
echo "              mprnet_motion_deblurring \\"
echo "              drbnet_defocus_deblurring"
echo ""

echo "=================================="
echo "💡 提示"
echo "=================================="
echo "1. 确保工具服务已启动（端口5001-5007）"
echo "2. 设置环境变量: export TOOL_SERVICE_IP=your.server.ip"
echo "3. GPU内存不足时，减少 max_samples 参数"
echo "4. 查看报告: cat output_dir/summary_report.txt"
echo "5. 查看详细数据: libreoffice output_dir/detailed_results.csv"
echo ""

