input = "upload_data/train.jsonl"

# Root directory for images (relative paths in JSONL will be resolved relative to this)
# root = "."
root = "/home/takisobe@amd.com/zxy/data/MVTec-2K"

# Output file path for the converted dataset
# output = "verl_crop_dataset.parquet"
output = "data/train/train_dataset.parquet"

# Output format: "parquet" or "jsonl"
format = "parquet"

limit = 0
