input = "upload_data/VisA/test/test.jsonl"

# Root directory for images (relative paths in JSONL will be resolved relative to this)
# root = "."
root = "/data/datasets/VisA-2K"

# Output file path for the converted dataset
# output = "verl_crop_dataset.parquet"
output = "data/visa/test/test_dataset.parquet"

# Output format: "parquet" or "jsonl"
format = "parquet"

limit = 0
