input = "/home/zxy/codes/working/RL/DeepEyes/data/mini/mini.jsonl"

# Root directory for images (relative paths in JSONL will be resolved relative to this)
# root = "."
root = "/data1/huggingface/hub/datasets--XimiaoZhang--MVTec-2K/snapshots/d52ff40b834d44cfcbea1fafc204666fc0da5b18"

# Output file path for the converted dataset
# output = "verl_crop_dataset.parquet"
output = "/home/zxy/codes/working/RL/DeepEyes/data/mini/mini_dataset.parquet"

# Output format: "parquet" or "jsonl"
format = "parquet"

limit = 0
